# ===============================
# = PARAMETERS  H2
# ===============================

# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core

# ===============================
# = DATA SOURCE
# ===============================
# UNIX or MAC
spring:
  profiles:
    active : h2

logging :
  # DEBUG, INFO , ERROR
  level :
    root : INFO

  # Output to a temp_folder/file
  file :
    name : ${user.home}/logs/application.log

  pattern :
  # Logging pattern for the console : IT IS OK
  # console : %d{yy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

  # Logging pattern for file : DONT WORK, DISABLE WRITE FILE LOG
  # file : %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%

server :
  port : 8080

